spring:
  profiles:
    active:

  ############################################################
  #
  # 自定义security默认用户名和密码
  #
  ############################################################
#  security:
#    user:
#      name: "user"
#      password: "123"



