spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: root
    password: 9958
  ############################################################
  #
  # 自定义security默认用户名和密码
  #
  ############################################################
#  security:
#    user:
#      name: "user"
#      password: "123"

  application:
    name: dubbo-spring-boot-starter
#  dubbo:
#    server: true
#    registry: zookeeper://127.0.0.1:2181
  ############################################################
  #
  # jpa资源配置
  #
  ############################################################
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #      ddl-auto: create #每次启动都会重新创建
      ddl-auto: update #如果表中有数据就不会重新创建
    show-sql: true

  ############################################################
  #
  # thymeleaf 热部署配置
  #
  ############################################################
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java
  #      exclude: static/**,public/** #排除那个目录的文件不需要restart


  ############################################################
  #
  # thymeleaf 静态资源配置
  #
  ############################################################
  thymeleaf:
    prefix: classpath:/templates/ #默认配置
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false

  ############################################################
  #
  # mybatis 配置
  #
  ############################################################
  # mybatis 配置
  mybatis:
    type-aliases-package: com.xmr.web.mubatis.pojo
    mapper-locations: classpath:mapper/*.xml
  # 通用 Mapper 配置
  mapper:
    #    mappers:  com.imooc.utils.MyMapper
    not-empty: false
    identity: MYSQL

netty:
  port: 7000
  url: 127.0.0.1

#rabbitmq:
#    host: 192.168.1.21
#
#activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: false
#      max-connections: 50
#  # 使用发布/订阅模式时，下边配置需要设置成 true
#  jms:
#      pub-sub-domain=false:


  ############################################################
  #
  # 使用Lombok框架的log配置
  #
  ############################################################
#logging:
#  level: info
#  path: /log

